# SPDX-License-Identifier: GPL-2.0-only
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
    labels: [dependencies]

  - package-ecosystem: pip
    directory: /Documentation
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
    labels: [dependencies]
