#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
#
# txt2c.sh NAME < input.txt > output.h
#
# Convert text file into a C string constant named NAME.
#
# Used to embed the default mouse art into the binary so
# alloyctl runs from any directory without install-path lookups.
set -eu

name="$1"

printf '/* Generated by tools/txt2c.sh - do not edit. */\n'
printf 'static const char %s[] =\n' "$name"
sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/\t"/' -e 's/$/\\n"/'
printf '\t;\n'
