// SPDX-License-Identifier: GPL-2.0-only
/*
 * Generate udev rules file for unprivileged /dev/hidraw* access.
 *
 * alloyctl talks to its mice through their raw HID node (/dev/hidraw*),
 * which is root-only by default on most distributions.
 *
 * Rather than ship a hand-kept list of vendor/product ids that drifts as drivers land,
 * the rules are built straight from the driver registry:
 *	one match line per supported device.
 *
 * Hidraw node's parent HID device is named "BBBB:VVVV:PPPP.NNNN" (bus, vendor, product,
 * instance - all uppercase hex), so matching KERNELS against that string pins each rule
 * to exactly one product on exactly one transport, covering both the USB/2.4 GHz receiver
 * (bus 0003) and Bluetooth (bus 0005) forms driver may register.
 */
#include "udev.h"

#include "driver.h"

/* HID bus number of the USB/2.4 GHz path (BUS_USB); registry stores 0 */
#define ALLOY_HID_BUS_USB 0x0003

void alloy_udev_rules_write(FILE *out)
{
	const struct alloy_driver *const *iter;

	fprintf(out,
		"# SPDX-License-Identifier: GPL-2.0-only\n"
		"#\n"
		"# alloyctl reaches SteelSeries mice through their raw HID node\n"
		"# (/dev/hidraw*), which is root-only by default. These rules grant\n"
		"# access to the active desktop session (uaccess, on logind systems)\n"
		"# and, as a fallback, to members of the \"input\" group.\n"
		"#\n"
		"# Generated by 'alloyctl --dump-udev' from the built-in driver\n"
		"# registry, so it lists exactly the devices this build supports.\n"
		"#\n"
		"# Install to /usr/lib/udev/rules.d/ (or /etc/udev/rules.d/) then reload:\n"
		"#   sudo udevadm control --reload && sudo udevadm trigger\n");

	alloy_for_each_driver(iter)
	{
		const struct alloy_driver *drv = *iter;
		unsigned bus = drv->bustype ? drv->bustype : ALLOY_HID_BUS_USB;

		fprintf(out, "\n# %s (%04x:%04x)\n", drv->name, drv->vendor_id,
			drv->product_id);
		fprintf(out,
			"KERNEL==\"hidraw*\", KERNELS==\"%04X:%04X:%04X.*\", "
			"TAG+=\"uaccess\", GROUP=\"input\", MODE=\"0660\"\n",
			bus, drv->vendor_id, drv->product_id);
	}
}
