// SPDX-License-Identifier: GPL-2.0-only
/*
 * Generate the udev rules the supported devices need.
 *
 * Core does not know which device nodes a driver ends up using - that is
 * property of its transport - so it walks the driver registry and asks each
 * driver's transport to describe its own access requirements.
 */
#include "udev.h"

#include <string.h>

#include "driver.h"

void alloy_udev_rules_write(FILE *out)
{
	const struct alloy_driver *const *iter;
	char buf[1024];

	fprintf(out,
		"# SPDX-License-Identifier: GPL-2.0-only\n"
		"#\n"
		"# alloyctl reaches its devices through raw device nodes that are\n"
		"# root-only by default. These rules grant access to the active\n"
		"# desktop session (uaccess, on logind systems).\n"
		"#\n"
		"# Generated by 'alloyctl --dump-udev' from the built-in driver\n"
		"# registry, so it lists exactly the devices this build supports.\n"
		"#\n"
		"# Install to /usr/lib/udev/rules.d/ (or /etc/udev/rules.d/) then reload:\n"
		"#   sudo udevadm control --reload && sudo udevadm trigger\n");

	alloy_for_each_driver(iter)
	{
		const struct alloy_driver *drv = *iter;
		const struct alloy_transport *tr =
			drv->transport ? drv->transport : &alloy_hid_transport;

		if (!tr->udev_rules)
			continue;
		buf[0] = '\0';
		if (!tr->udev_rules(drv, buf, sizeof(buf)))
			continue;
		fputc('\n', out);
		fputs(buf, out);
	}
}
